#!/usr/bin/env bash
set -euo pipefail

# Architecture visualization generator
# Usage: ./scripts/gen-arch.sh  (or: make arch)
#
# Generates:
#   docs/architecture/pkg-deps.svg    — package dependency graph
#   docs/architecture/structs.svg     — struct/interface relationship diagram
#   docs/architecture/modules.md      — module index with line counts
#   docs/architecture/index.html      — dashboard (view all in browser)

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/docs/architecture/generated"
MODULE="$(head -1 "$ROOT/go.mod" | awk '{print $2}')"

mkdir -p "$OUT"

echo "==> Generating package dependency graph..."
cd "$ROOT"
goda graph "$MODULE/internal/..." > "$OUT/pkg-deps.dot" 2>/dev/null

# Strip module prefix for cleaner labels
sed -i '' "s|$MODULE/||g" "$OUT/pkg-deps.dot"

dot -Tsvg "$OUT/pkg-deps.dot" -o "$OUT/pkg-deps.svg"
echo "    -> pkg-deps.svg"

echo "==> Generating struct relationship diagram..."
goplantuml -recursive "$ROOT/internal" > "$OUT/structs.puml"

# Convert PlantUML to dot then SVG
# Since plantuml jar may not be available, generate a simplified dot from the puml
python3 - "$OUT/structs.puml" "$OUT/structs.dot" << 'PYEOF'
import sys, re

puml_path, dot_path = sys.argv[1], sys.argv[2]

with open(puml_path) as f:
    content = f.read()

nodes = {}
edges = []
current_ns = ""

for line in content.split("\n"):
    line = line.strip()

    # namespace
    m = re.match(r'namespace\s+(\w+)', line)
    if m:
        current_ns = m.group(1)
        continue

    # class/interface
    m = re.match(r'class\s+"(\w+)"', line)
    if not m:
        m = re.match(r'interface\s+"(\w+)"', line)
    if m:
        name = m.group(1)
        full = f"{current_ns}.{name}" if current_ns else name
        shape = "record" if "interface" not in line.lower() else "ellipse"
        nodes[full] = {"name": name, "ns": current_ns, "shape": shape}
        continue

    # composition/aggregation
    m = re.match(r'"?(\w+)"?\s*[*o]-+[>|]\s*"?(\w+)"?', line)
    if m:
        edges.append((m.group(1), m.group(2)))

lines = ['digraph structs {']
lines.append('  node [shape=record fontsize=10 fontname="Helvetica"];')
lines.append('  edge [fontsize=9];')
lines.append('  rankdir=LR;')
lines.append('  newrank=true;')
lines.append('')

# Group by namespace
by_ns = {}
for full, info in nodes.items():
    by_ns.setdefault(info["ns"], []).append(info)

for ns, items in sorted(by_ns.items()):
    lines.append(f'  subgraph cluster_{ns} {{')
    lines.append(f'    label="{ns}";')
    lines.append(f'    style=rounded;')
    lines.append(f'    color="#666666";')
    for item in items:
        nid = f'{ns}_{item["name"]}'
        lines.append(f'    "{nid}" [label="{item["name"]}" shape={item["shape"]}];')
    lines.append('  }')
    lines.append('')

for src, dst in edges:
    lines.append(f'  "{src}" -> "{dst}";')

lines.append('}')

with open(dot_path, 'w') as f:
    f.write('\n'.join(lines))
PYEOF

dot -Tsvg "$OUT/structs.dot" -o "$OUT/structs.svg"
echo "    -> structs.svg"

echo "==> Generating module index..."
cat > "$OUT/modules.md" << 'MDEOF'
# Module Index

> Auto-generated by `make arch`. Do not edit manually.

MDEOF

# Walk internal/ packages
cd "$ROOT"
for pkg_dir in $(find internal -type d | sort); do
    go_files=$(find "$pkg_dir" -maxdepth 1 -name "*.go" 2>/dev/null | grep -v _test.go || true)
    if [ -z "$go_files" ]; then
        continue
    fi

    # Package name from first go file
    pkg_name=$(head -5 $(echo "$go_files" | head -1) | grep "^package " | awk '{print $2}')

    # Line count
    total_lines=$(cat $go_files | wc -l | tr -d ' ')

    # File list with individual line counts
    file_details=""
    for f in $go_files; do
        fname=$(basename "$f")
        flines=$(wc -l < "$f" | tr -d ' ')
        file_details="$file_details  - \`$fname\` ($flines lines)\n"
    done

    # Package doc comment (first // or /* comment block)
    doc=$(head -20 $(echo "$go_files" | head -1) | grep "^//" | head -3 | sed 's|^// *||')

    # Exports
    exports=$(grep -h "^func \|^type \|^var \|^const " $go_files 2>/dev/null \
        | grep -v "^func (" \
        | sed 's/{.*//' \
        | head -10 || true)

    # Methods on exported types
    methods=$(grep -h "^func (" $go_files 2>/dev/null \
        | sed 's/{.*//' \
        | head -10 || true)

    {
        echo "## \`$pkg_dir\` (package $pkg_name) — $total_lines lines"
        if [ -n "$doc" ]; then
            echo ""
            echo "> $doc"
        fi
        echo ""
        echo "Files:"
        echo -e "$file_details"
        if [ -n "$exports" ]; then
            echo "Exports:"
            echo '```go'
            echo "$exports"
            echo '```'
            echo ""
        fi
        if [ -n "$methods" ]; then
            echo "Methods:"
            echo '```go'
            echo "$methods"
            echo '```'
            echo ""
        fi
        echo "---"
        echo ""
    } >> "$OUT/modules.md"
done

echo "    -> modules.md"

echo "==> Done! Open docs/architecture/generated/index.html in browser."
